spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      #      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: chaoxing
      #      url: jdbc:mysql://120.131.6.144:3306/cultural_gallery?serverTimezone=UTC&characterEncoding=UTF-8
      #      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/ovp?serverTimezone=GMT%2B8&characterEncoding=UTF-8
      url: jdbc:mysql://127.0.0.1:3306/sendmessage?serverTimezone=GMT%2B8&characterEncoding=UTF-8


      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"





    dbcp2:
      initial-size: 20
      min-evictable-idle-time-millis: 3600000
      default-auto-commit: true
    tomcat:
      max-active: 50
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  servlet:
    context-path: /
  port: 9000

logging:
  level:
    com.chaoxing.dao: trace


#原数据配置文件
mybatis:
  typeAliasesPackage: com.laishishui.sendmessage.bean.po
  mapper-locations: classpath:mappers/*.xml
# 开启接口文档.生产关掉
swagger:
  enable: true



lsp:
  primaryId: 2
  libCode: 2222001
  clientId: 2222
  clientSecret: 6565564