spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      #      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: chaoxing
      #      url: jdbc:mysql://120.131.6.144:3306/cultural_gallery?serverTimezone=UTC&characterEncoding=UTF-8
      #      url: jdbc:log4jdbc:mysql://127.0.0.1:3306/ovp?serverTimezone=GMT%2B8&characterEncoding=UTF-8
      url: jdbc:mysql://127.0.0.1:3306/shell_no?serverTimezone=GMT%2B8&characterEncoding=UTF-8


      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"





    dbcp2:
      initial-size: 20
      min-evictable-idle-time-millis: 3600000
      default-auto-commit: true
    tomcat:
      max-active: 50
#spring:
#  datasource:
#    oracle:
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      username: weiruan
#      password: wr123456
#      jdbc-url: jdbc:oracle:thin:@31.0.178.216:1521:swshare
#    jpa:
#      show-sql: true
#    jackson:
#      default-property-inclusion: non_null
#spring:
#  datasource:
#    sqlserver:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      username: weiruan
#      password: wr@123456
#      jdbc-url: jdbc:sqlserver://31.0.178.146:1433
#    jpa:
#      show-sql: true
#    jackson:
#      default-property-inclusion: non_null
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

server:
  servlet:
    context-path: /
  port: 9000

logging:
  level:
    com.chaoxing.dao: trace


#原数据配置文件
mybatis:
  typeAliasesPackage: com.laishishui.rfidtopjh.bean.po
  mapper-locations: classpath:mappers/*.xml
# 开启接口文档.生产关掉
swagger:
  enable: true


#  type =1  接口是.com  type=2  接口是.cn    primaryId   是工作人员账号 例如 tsgadmin
lsp:
  cntype: 1
  primaryId: tsgadmin
  libCode: 20004900001
  clientId: 519dadf6b24a4816b79d684c3489277c
  clientSecret: d1dd716cd2fe49d3835d97fe6e01ea73